# Generated by Django 2.0.5 on 2018-05-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='location',
            new_name='latitude',
        ),
        migrations.AlterField(
            model_name='city',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
