# Generated by Django 2.0.5 on 2018-06-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='woeid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
