# Generated by Django 2.0.5 on 2018-06-27 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180624_1735'),
        ('api', '0009_profile'),
    ]

    operations = [
    ]
