# Generated by Django 2.0.5 on 2018-07-03 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_notification'),
        ('api', '0012_auto_20180702_1510'),
    ]

    operations = [
    ]
