# Generated by Django 2.0.5 on 2018-07-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180702_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityvisitlog',
            name='visit_count',
            field=models.IntegerField(default=0),
        ),
    ]
