# Generated by Django 2.0.5 on 2018-07-03 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_cityvisitlog_visit_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityvisitlog',
            name='visit_count',
        ),
    ]
