# Generated by Django 2.0.5 on 2018-07-05 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_merge_20180703_1550'),
        ('api', '0014_remove_cityvisitlog_visit_count'),
    ]

    operations = [
    ]
