# Generated by Django 2.0.5 on 2018-07-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_notification_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unique_code',
            field=models.TextField(default=None, null=True),
        ),
    ]
