# Generated by Django 2.0.5 on 2018-10-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_profile_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='nickname',
            field=models.TextField(blank=True, null=True),
        ),
    ]
